spring:
  application:
    name: order-service
  data:
    mongodb:
      database: ORDER-INFO
  mongodb:
    data:
      uri: mongodb://localhost:27017/ORDER-INFO
      collection: ORDER
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    #register eureka as application
    register-with-eureka: true
    #fetch all thing, we can get applications here
    fetch-registry: true
    #also you can specify the instance renewal time.
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}